server:
  port: 8083
  servlet:
    encoding:
      force-response: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.11:3307/pookydb?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Seoul
    username: pooky
    password: pooky@#4002511

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
        show_sql: true

logging:
  level:
    org.hibernate.SQL: debug # logger에 출력하려면
    org.hibernate.type.descriptor.sql: trace # 파라미터 값 출력

jwt:
  secret: "AmKMSyFs3PLnjnUJ+eVEQhushSxVP304msrFm4rj6PA="
  expiration: 86400000 #1일