server:
  port: 8080
  servlet:
    encoding:
      force-response: true

spring:
  #H2 DB ??
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:tcp://localhost/~/pookyBlog'
    username: pooky
    password: asdfasdf

  h2:
    console:
      enabled: true       #H2 Console ?? ??
      path: /h2-console   #H2 Console ?? ??

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true    #?? ?? ?? (??)
        show_sql: true      #?? ?? ??

logging:
  level:
    org.hibernate.SQL: debug # logger에 출력하려면
    org.hibernate.type.descriptor.sql: trace # 파라미터 값 출력

jwt:
  secret: "AmKMSyFs3PLnjnUJ+eVEQhushSxVP304msrFm4rj6PA="
  expiration: 86400000 #1일