plugins {
    id 'java'
    id 'org.springframework.boot' version '3.4.0' // Spring Boot 플러그인 추가
    id 'io.spring.dependency-management'
}
dependencies {
    implementation project(':common')
    implementation project(':common:snowflake')
    implementation project(':common:outboxmessage')
    implementation project(':services:user')
    implementation 'mysql:mysql-connector-java:8.0.33'
    implementation 'org.springframework.boot:spring-boot-starter-security'

    testImplementation 'org.springframework.security:spring-security-test'
    testImplementation 'org.springframework.kafka:spring-kafka'
    testImplementation 'org.awaitility:awaitility:4.2.0' // 또는 최신 버전
}

sourceSets {
    performanceTest {
        java.srcDir 'src/performanceTest/java'
        resources.srcDir 'src/test/resources'
        compileClasspath += sourceSets.main.output
        runtimeClasspath += sourceSets.main.output
    }
}

configurations {
    performanceTestImplementation.extendsFrom testImplementation
    performanceTestRuntimeOnly.extendsFrom testRuntimeOnly
}

tasks.register('performanceTest', Test) {
    description = 'Runs the post service performance and bulk-data tests.'
    group = 'verification'
    testClassesDirs = sourceSets.performanceTest.output.classesDirs
    classpath = sourceSets.performanceTest.runtimeClasspath
    useJUnitPlatform()
    shouldRunAfter tasks.named('test')
}

bootJar{
    enabled = true
}
