server:
  port: 8087
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    hibernate:
#      ddl-auto: none # ❗ web 모듈은 DB에 직접 쓰지 않으므로 none 또는 validate
#    properties:
#      hibernate:
#        show_sql: false
#        format_sql: false

jwt:
  secret: "AmKMSyFs3PLnjnUJ+eVEQhushSxVP304msrFm4rj6PA="
  expiration: 86400000 #1일
auth:
  cookie:
    secure: false
    same-site: Strict
    max-age: 3600

logging:
  level:
    org.springframework.web: debug

service:
  url:
    comment: http://localhost:8080
    hot-post: http://localhost:8081
    like: http://localhost:8082
    post: http://localhost:8083
    post-read: http://localhost:8086
    user: http://localhost:8084
    view: http://localhost:8085
